import fr from './i18n/fr.js';import en from './i18n/en.js';
const dictionaries={fr,en};
const safeStore={get(k,d){try{return localStorage.getItem(k)??d}catch{return d}},set(k,v){try{localStorage.setItem(k,v)}catch{}}};
const state={lang:safeStore.get('fart.lang','fr'),view:'home',recording:false,elapsed:0,db:null,interval:null,playingId:null,next:4,sounds:[{id:'1',name:'Fart cosmique',duration:2.8,date:'2026-09-15',rating:4,trimStart:0,trimEnd:2.8},{id:'2',name:'Petit nuage',duration:1.6,date:'2026-09-14',rating:2,trimStart:0,trimEnd:1.6},{id:'3',name:'Turbo discret',duration:3.4,date:'2026-09-12',rating:0,trimStart:0,trimEnd:3.4}],query:'',sort:'recent'};
const app=document.querySelector('#app'),toast=document.querySelector('#toast');let modalCleanup=null;const t=k=>dictionaries[state.lang][k]??k;
function showToast(msg){toast.textContent=msg;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),1800)}
function header(){return `<header class="topbar"><div class="brand"><div class="logo">F</div><div><h1>Fart</h1><p class="eyebrow">${t('demo')}</p></div></div><button class="lang-btn" data-action="lang" aria-label="Changer la langue">${state.lang.toUpperCase()}</button></header>`}
function nav(){return `<nav class="bottom-nav"><button class="nav-btn ${state.view==='home'?'active':''}" data-nav="home">🎙️ ${t('home')}</button><button class="nav-btn ${state.view==='library'?'active':''}" data-nav="library">🎵 ${t('library')}</button></nav>`}
function home(){return `<main class="view hero"><div class="wave-stage" id="stage"><div class="blob" id="blob"></div><button class="record-btn" id="record" aria-label="${t('hold')}">🎙️</button></div><div class="timer-row"><span class="timer" id="timer">0:00.0</span><span class="db" id="db">-- dB</span></div><h2 class="hero-title" id="status">${t('hold')}</h2><p class="sub" id="hint">${t('release')}</p><p class="demo-note">${t('visual')}</p></main>`}
function formatTime(s){const m=Math.floor(s/60),sec=(s%60).toFixed(1).padStart(4,'0');return `${m}:${sec}`}
function library(){let list=[...state.sounds].filter(s=>s.name.toLowerCase().includes(state.query.toLowerCase()));if(state.sort==='rating')list.sort((a,b)=>b.rating-a.rating);else if(state.sort==='alpha')list.sort((a,b)=>a.name.localeCompare(b.name,state.lang));else list.sort((a,b)=>b.date.localeCompare(a.date));return `<main class="view"><div class="section-head"><h2>${t('library')}</h2><div class="count">${state.sounds.length} / 100 ${t('sounds')}</div></div><div class="tools"><input class="field" id="search" value="${escapeHtml(state.query)}" placeholder="${t('search')}"><select id="sort"><option value="recent" ${state.sort==='recent'?'selected':''}>${t('recent')}</option><option value="rating" ${state.sort==='rating'?'selected':''}>${t('ratingSort')}</option><option value="alpha" ${state.sort==='alpha'?'selected':''}>${t('alpha')}</option></select></div><div class="sound-list">${list.length?list.map(card).join(''):`<div class="empty">🎧<br><br>${t('empty')}</div>`}</div></main>`}
function card(s){return `<article class="sound-card"><div class="sound-top"><button class="play" data-play="${s.id}" aria-label="Lecture">${state.playingId===s.id?'⏸':'▶'}</button><div class="sound-info"><div class="sound-name">${escapeHtml(s.name)}</div><div class="meta">${formatTime(s.trimEnd-s.trimStart)} · ${new Intl.DateTimeFormat(state.lang).format(new Date(s.date))}</div></div><button class="more" data-detail="${s.id}" aria-label="${t('details')}">•••</button><button class="more" data-delete="${s.id}" aria-label="${t('delete')}">🗑️</button></div>${rating(s)}</article>`}
function rating(s){return `<div class="rating" aria-label="Note ${s.rating} sur 5">${[1,2,3,4,5].map(n=>`<button data-rate="${s.id}:${n}" aria-label="${n} sur 5">(${n<=s.rating?'o':'x'})</button>`).join('')}</div>`}
function render(){app.innerHTML=header()+(state.view==='home'?home():library())+nav();bind()}
function bind(){document.querySelectorAll('[data-nav]').forEach(b=>b.onclick=()=>{stopRecording(false);state.view=b.dataset.nav;render()});document.querySelector('[data-action="lang"]').onclick=()=>{state.lang=state.lang==='fr'?'en':'fr';safeStore.set('fart.lang',state.lang);render()};if(state.view==='home')bindRecord();else bindLibrary()}
function bindRecord(){const btn=document.querySelector('#record');const begin=e=>{e.preventDefault();if(state.recording)return;state.recording=true;state.elapsed=0;document.querySelector('#stage').classList.add('recording');tick();state.interval=setInterval(tick,100)};const end=e=>{e?.preventDefault();if(state.recording)stopRecording(true)};btn.addEventListener('pointerdown',begin);window.addEventListener('pointerup',end,{once:true});window.addEventListener('pointercancel',end,{once:true})}
function tick(){state.elapsed=Math.min(20,state.elapsed+.1);state.db=-Math.round(9+Math.random()*38);const intensity=Math.max(0,Math.min(1,(state.db+48)/39));document.querySelector('#timer').textContent=formatTime(state.elapsed);document.querySelector('#db').textContent=`${state.db} dB`;document.querySelector('#status').textContent=t('recording');document.querySelector('#blob').style.setProperty('--blob-scale',String(1+intensity*.16));document.querySelector('#blob').style.setProperty('--blob-rotate',`${(Math.random()-.5)*9}deg`);if(state.elapsed>=20)stopRecording(true)}
function stopRecording(open){if(!state.recording)return;state.recording=false;clearInterval(state.interval);state.interval=null;if(open)previewModal()}
function bars(){return Array.from({length:34},(_,i)=>`<i class="bar" style="--h:${22+Math.abs(Math.sin(i*.73))*65}%"></i>`).join('')}
function modal(content){if(modalCleanup)modalCleanup();const wrap=document.createElement('div');wrap.className='modal-backdrop';wrap.innerHTML=`<section class="modal" role="dialog" aria-modal="true">${content}</section>`;document.body.append(wrap);modalCleanup=()=>{wrap.remove();modalCleanup=null};return wrap}
function previewModal(){const auto=`Fart ${String(state.next).padStart(3,'0')}`;const w=modal(`<h2>${t('preview')}</h2><p class="sub">${t('previewHelp')}</p><div class="preview-wave">${bars()}</div><button class="secondary" id="previewPlay">▶ ${t('listen')}</button><label><span class="meta">${t('name')}</span><input class="field" id="previewName" value="${auto}" maxlength="60"></label><div class="modal-actions"><button class="danger" id="discard">🗑️ ${t('discard')}</button><button class="primary" id="save">${t('save')}</button></div>`);let playing=false;w.querySelector('#previewPlay').onclick=e=>{playing=!playing;e.currentTarget.textContent=playing?`⏸ ${t('pause')}`:`▶ ${t('listen')}`};w.querySelector('#discard').onclick=()=>confirmModal(t('discardTitle'),t('discardBody'),()=>{modalCleanup();render()});w.querySelector('#save').onclick=()=>{const name=w.querySelector('#previewName').value.trim()||auto;state.sounds.push({id:crypto.randomUUID?.()||String(Date.now()),name,duration:Math.max(.3,state.elapsed),date:new Date().toISOString().slice(0,10),rating:0,trimStart:0,trimEnd:Math.max(.3,state.elapsed)});state.next++;modalCleanup();render();showToast(t('saved'))}}
function bindLibrary(){const search=document.querySelector('#search'),sort=document.querySelector('#sort');search.oninput=()=>{state.query=search.value;render()};sort.onchange=()=>{state.sort=sort.value;render()};document.querySelectorAll('[data-rate]').forEach(b=>b.onclick=()=>{const [id,n]=b.dataset.rate.split(':');const s=state.sounds.find(x=>x.id===id);s.rating=s.rating===+n?0:+n;render()});document.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>deleteSound(b.dataset.delete));document.querySelectorAll('[data-detail]').forEach(b=>b.onclick=()=>detailModal(b.dataset.detail));document.querySelectorAll('[data-play]').forEach(b=>b.onclick=()=>{state.playingId=state.playingId===b.dataset.play?null:b.dataset.play;render()})}
function confirmModal(title,body,onYes){const w=modal(`<h2>${title}</h2><p>${body}</p><div class="modal-actions"><button class="secondary" id="no">${t('cancel')}</button><button class="danger" id="yes">${t('delete')}</button></div>`);w.querySelector('#no').onclick=()=>modalCleanup();w.querySelector('#yes').onclick=onYes}
function deleteSound(id){confirmModal(t('deleteTitle'),t('deleteBody'),()=>{state.sounds=state.sounds.filter(s=>s.id!==id);modalCleanup();render();showToast(t('deleted'))})}
function detailModal(id){const s=state.sounds.find(x=>x.id===id);const w=modal(`<h2>${t('details')}</h2><div class="preview-wave">${bars()}</div><h3>${escapeHtml(s.name)}</h3><p class="meta">${t('date')} : ${new Intl.DateTimeFormat(state.lang).format(new Date(s.date))}<br>${t('duration')} : ${formatTime(s.trimEnd-s.trimStart)}</p>${rating(s)}<div class="detail-grid"><button class="detail-action" id="rename">✏️ ${t('rename')}</button><button class="detail-action" id="trim">✂️ ${t('trim')}</button><button class="detail-action" id="export">⬇️ ${t('export')}</button><button class="detail-action" id="del">🗑️ ${t('delete')}</button></div><div class="modal-actions"><button class="primary" id="close">${t('back')}</button></div>`);w.querySelector('#close').onclick=()=>modalCleanup();w.querySelector('#rename').onclick=()=>renameModal(id);w.querySelector('#trim').onclick=()=>trimModal(id);w.querySelector('#del').onclick=()=>{modalCleanup();deleteSound(id)};w.querySelector('#export').onclick=()=>showToast(t('visual'))}
function renameModal(id){const s=state.sounds.find(x=>x.id===id);const w=modal(`<h2>${t('rename')}</h2><input class="field" id="newName" value="${escapeHtml(s.name)}" maxlength="60"><div class="modal-actions"><button class="secondary" id="cancel">${t('cancel')}</button><button class="primary" id="ok">${t('validate')}</button></div>`);w.querySelector('#cancel').onclick=()=>detailModal(id);w.querySelector('#ok').onclick=()=>{s.name=w.querySelector('#newName').value.trim()||`Fart ${String(state.next++).padStart(3,'0')}`;modalCleanup();render();showToast(t('renamed'))}}
function trimModal(id){const s=state.sounds.find(x=>x.id===id);let a=s.trimStart,b=s.trimEnd;const w=modal(`<h2>${t('trimTitle')}</h2><div class="trim-box"><div class="trim-wave">${bars()}</div><div class="shade left" id="leftShade"></div><div class="shade right" id="rightShade"></div></div><div class="trim-controls"><label>Début <input id="start" type="range" min="0" max="${s.duration}" step="0.1" value="${a}"></label><label>Fin <input id="end" type="range" min="0" max="${s.duration}" step="0.1" value="${b}"></label></div><p id="selection"></p><button class="secondary" id="restore">${t('restore')}</button><div class="modal-actions"><button class="secondary" id="cancel">${t('cancel')}</button><button class="primary" id="ok">${t('validate')}</button></div>`);const start=w.querySelector('#start'),end=w.querySelector('#end');function update(changed){a=+start.value;b=+end.value;if(b-a<.3){if(changed==='start')a=Math.max(0,b-.3);else b=Math.min(s.duration,a+.3);start.value=a;end.value=b}w.querySelector('#leftShade').style.width=`${a/s.duration*100}%`;w.querySelector('#rightShade').style.width=`${(s.duration-b)/s.duration*100}%`;w.querySelector('#selection').textContent=`${formatTime(b-a)}`};start.oninput=()=>update('start');end.oninput=()=>update('end');w.querySelector('#restore').onclick=()=>{start.value=0;end.value=s.duration;update()};w.querySelector('#cancel').onclick=()=>detailModal(id);w.querySelector('#ok').onclick=()=>{s.trimStart=a;s.trimEnd=b;modalCleanup();render();showToast(t('trimSaved'))};update()}
function escapeHtml(v){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
render();